docker info: fix connection errors and exit code being discarded
Check whether `formatInfo` or `prettyPrintInfo` handled the error, otherwise
return it. Previously we'd print the error, but the function may not have
handled the error if a template was used that didn't consume the ServerErrors
field.

Before;

    docker -H example.invalid info > /dev/null
    ERROR: error during connect: Get "http://example.invalid:2375/v1.48/info": dial tcp: lookup example.invalid: no such host
    errors pretty printing info
    echo $?
    1

    docker -H example.invalid info --format '{{.Architecture}}' > /dev/null
    error during connect: Get "http://example.invalid:2375/v1.48/info": dial tcp: lookup example.invalid: no such host

    echo $?
    0

    # invalid template
    docker -H example.invalid info --format '{{.Whoops}}' > /dev/null
    error during connect: Get "http://example.invalid:2375/v1.48/info": dial tcp: lookup example.invalid: no such host
    template: :1:2: executing "" at <.Whoops>: cant evaluate field Whoops in type system.dockerInfo
    echo $?
    1

After;

    docker -H example.invalid info > /dev/null
    ERROR: error during connect: Get "http://example.invalid:2375/v1.48/info": dial tcp: lookup example.invalid: no such host
    errors pretty printing info

    echo $?
    1

    docker -H example.invalid info --format '{{.Architecture}}' > /dev/null
    error during connect: Get "http://example.invalid:2375/v1.48/info": dial tcp: lookup example.invalid: no such host

    echo $?
    1

    docker -H example.invalid info --format '{{.Whoops}}' > /dev/null
    error during connect: Get "http://example.invalid:2375/v1.48/info": dial tcp: lookup example.invalid: no such host
    template: :1:2: executing "" at <.Whoops>: cant evaluate field Whoops in type system.dockerInfo

    echo %?
    1

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>